[versions]
agp = "8.9.2"
kotlin = "2.1.20"
ksp = "2.1.20-2.0.0"
android-core = "1.16.0"
android-lifecycle-runtime = "2.8.7"
compose-activity = "1.10.1"
compose-ui = "1.8.0"
datastore = "1.1.3"
timber = "5.0.1"
hilt = "2.56.1"
hilt-compose = "1.2.0"
hilt-compiler = "1.2.0"

[libraries]
android-core = { module = "androidx.core:core-ktx", version.ref = "android-core" }
android-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "android-lifecycle-runtime" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-ui" }

datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

